spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/localhost?serverTimezone=GMT%2B8
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5


#mybatis扫描包
mybatis:
  type-aliases-package: com.example.taskdemo.entity
  #Mapper指定扫描包
#  mapper-locations: classpath*:**/repeat/**/*Include.xml,classpath*:**/mapper/xml/**/*.xml
